# Generated by Django 2.2.5 on 2019-09-25 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, verbose_name='语言')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('birth', models.DateField(verbose_name='生日')),
                ('degree', models.CharField(max_length=10, verbose_name='学位')),
                ('sites', models.CharField(max_length=20, verbose_name='网站')),
                ('email', models.EmailField(max_length=254, verbose_name='邮件')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('img', models.ImageField(null=True, upload_to='user/info/%Y/%m/%d', verbose_name='头像')),
                ('img_head', models.ImageField(null=True, upload_to='', verbose_name='照片')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '基本信息',
                'verbose_name_plural': '基本信息',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, verbose_name='公司名称')),
                ('started', models.DateField(verbose_name='入职时间')),
                ('ended', models.DateField(blank=True, null=True, verbose_name='离职时间')),
                ('title', models.CharField(max_length=20, verbose_name='岗位职称')),
                ('description', models.CharField(max_length=30, verbose_name='岗位描述')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='更新时间')),
                ('created', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.UserInfo')),
            ],
            options={
                'verbose_name': '工作经验',
                'verbose_name_plural': '工作经验',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10, verbose_name='掌握程度')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='更新时间')),
                ('created', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Program', verbose_name='语言')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.UserInfo')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('img', models.ImageField(null=True, upload_to='user/info/%Y/%m/%d', verbose_name='项目图片')),
                ('cleent', models.CharField(max_length=50, null=True, verbose_name='客户')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='更新时间')),
                ('created', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('tags', models.ManyToManyField(to='resume.Program', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.UserInfo')),
            ],
            options={
                'verbose_name': '项目经验',
                'verbose_name_plural': '项目经验',
            },
        ),
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=20, verbose_name='学校名称')),
                ('started', models.DateField(verbose_name='入学时间')),
                ('ended', models.DateField(blank=True, null=True, verbose_name='毕业时间')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('madescriptionjor', models.CharField(max_length=20, verbose_name='专业描述')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='更新时间')),
                ('created', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.UserInfo')),
            ],
            options={
                'verbose_name': '教育经验',
                'verbose_name_plural': '教育经验',
            },
        ),
    ]
